# Generated by Django 5.0.6 on 2024-07-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(max_length=100)),
                ('Picture', models.ImageField(upload_to='works/')),
                ('Description', models.CharField(max_length=400)),
            ],
        ),
    ]
